### ISSUE TITLE
On library website, replace Google search box with link to the public UI (Friday 9am meeting)

### ISSUE THREAD

**Issue by reliztrent** [gwu-libraries/aspace-pui#16]
On all SCRC pages on the Library's website (library.gwu.edu/scrc), there is a Google search box for searching the flat XML finding aids. There is also a button sending users to the ASpace public UI. 

The Google search box should be removed, and the button wording should be updated. OR consider replacing the button with something that integrates the ASpace public UI better.

**Comment by reliztrent** [comment]
Wait to do until we're ready to push everything to production.

**Comment by maxstarkenburg** [comment]
The Drupal [block formerly](https://library.gwu.edu/admin/structure/block/manage/block/109/configure) on the sidebar of most SCRC pages has been retired and replaced with a [new block](https://library.gwu.edu/admin/structure/block/manage/block/137/configure) with a button to searcharchives (new block since the old one had styling specific to it that we no longer wanted). 

And the [larger block formerly](https://library.gwu.edu/admin/structure/block/manage/block/108/configure) on /scrc/search and /scrc/search//finding-aids-by-topic has been retired, and the button to searcharchives has been added directly to the content of those two pages.

Calling this one closed. Let me know if further wording adjustments are needed.
